name: "Terraform Apply"

on:
  push:
    branches:
      - master
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_apply_prod:
    name: "Tofu Apply - Prod"
    uses: ./.github/workflows/opentofu-apply.yml
    with:
      environment: prod
      opentofu_backend_config: |
        bucket=opentofu-state-pytorch
        dynamodb_table=opentofu-state-pytorch
    secrets:
      env_secret: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      opentofu_secret_variables: |
        datadog_api_key = "${{ secrets.DD_API_KEY }}"
        datadog_app_key = "${{ secrets.DD_APP_KEY }}"
