name: "Tofu Plan"

on:
  - pull_request

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_plan:
    name: "Tofu Plan"
    strategy:
      matrix:
        environment:
          - prod
    uses: ./.github/workflows/opentofu-plan.yml
    with:
      environment: ${{ matrix.environment }}
      opentofu_backend_config: |
        bucket=opentofu-state-pytorch-datadog
        dynamodb_table=opentofu-state-pytorch-datadog
    secrets:
      env_secret: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      opentofu_secret_variables: |
        datadog_api_key = "${{ secrets.DD_API_KEY }}"
        datadog_app_key = "${{ secrets.DD_APP_KEY }}"
