# SPDX-FileCopyrightText: 2025 2025 The Linux Foundation
#
# SPDX-License-Identifier: Apache-2.0

name: "Tofu Apply"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_apply_prod:
    name: "Tofu Apply - Prod"
    uses: ./.github/workflows/opentofu-apply.yml
    with:
      environment: prod
      opentofu_backend_config: |
        bucket=opentofu-state-pytorch-datadog
        dynamodb_table=opentofu-state-pytorch-datadog
    secrets:
      env_secret: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      opentofu_secret_variables: |
        datadog_api_key = "${{ secrets.DD_API_KEY }}"
        datadog_app_key = "${{ secrets.DD_APP_KEY }}"
        incident_io_bearer = "${{ secrets.INCIDENT_IO_BEARER }}"
